### ISSUE TITLE
Exclude routes

### ISSUE THREAD

**Issue by philipeatela** [natahouse/react-snap#1]
Add configuration option to prevent certain routes from being crawled.

References: https://github.com/stereobooster/react-snap/issues/362, https://github.com/stereobooster/react-snap/pull/165

**Comment by Valerika** [comment]
Hi @HigorAlves @philipeatela! Exclude not worked for me.

My settings for react-snap:
```
"reactSnap": {
    "source": "www",
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--unlimited-storage",
      "--full-memory-crash-report",
      "--disable-dev-shm-usage",
      "--disable-gpu",
      "--headless",
      "--disable-extensions"
    ],
    "skipThirdPartyRequests": true,
    "enableLogging": true,
    "removeScriptTags": true,
    "exclude": [
      "/funds/*",
      "/referral"
    ]
  }
```

**Comment by xavierraffin** [comment]
@Valerika This is probably because you are not using the master branch of this fork.

If you install it like that it will work:

```
npm install --save-dev https://github.com/natahouse/react-snap/tarball/master
```

But this is not ideal you can +1 this: https://github.com/natahouse/react-snap/issues/26

**Comment by Valerika** [comment]
@xavierraffin thanks!

Have you encountered the issue of scripts with chunks in static html files? 
When deploying, I have a problem, because the html file refers to the previous script with a chunk hash. 
The problem is solved by clearing the cache.
