### ISSUE TITLE
Publish a package

### ISSUE THREAD

**Issue by xavierraffin** [natahouse/react-snap#26]
## Feature Request

It will be nice if you could publish a npm package on npm registry or Github packages with a tag.

I am importing your project like that: 

```
npm install --save-dev https://github.com/natahouse/react-snap/tarball/master
```

This is risky because you may break my build if you push something new.

**Describe alternatives you've considered**

Forking again myself and publishing it.

**Comment by maxzinchenko** [comment]
+1

**Comment by philipeatela** [comment]
I had it published a while back but forgot to update the Readme package with the new link: https://www.npmjs.com/package/react-snap-nh

Closing it for now, let me know if you have issues installing it from the package.
